name: Test

on:
  pull_request:
    branches: [main]
    paths:
      - 'src/lib/**'
      - 'package.json'
      - 'vite.config.ts'
      - 'svelte.config.js'
      - 'tsconfig.json'

jobs:
  test:
    uses: WJSoftware/cicd/.github/workflows/npm-test.yml@main
    with:
      node-version: 24
      build-script: build
      test-script: test
      build: false
