name: Test

on:
  pull_request:
    branches: [ main ]
    paths-ignore:
      - 'docs/**'
      - 'playground/**'
      - '.github/**'
      - 'README.md'
      - 'LICENSE'
      - '.gitignore'
      - 'eslint.config.js'
      - 'add-component-help.ps1'
      - 'AGENTS.md'
      - '.prettierrc'
      - '.prettierignore'
      - 'src/lib/routes/**'
      - 'static/**'

jobs:
  test:
    uses: WJSoftware/cicd/.github/workflows/npm-test.yml@main
    with:
      node-version: 24
      build-script: build
      test-script: test
      build: false
